name: Create release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          preset: conventionalcommits
          version-file: "custom_components/ferroamp/manifest.json"
          pre-changelog-generation: "./.github/scripts/tagname.js"

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.github_token }}
          commit: ${{ github.sha }}
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          name: ${{ steps.changelog.outputs.tag }}
